// Re-export business data collector
export { getBusinessDataForAI } from "./businessDataCollector";

// Re-export Firebase service functions
// All functions are now async and use Firebase Firestore instead of localStorage
export {
  getCompanyProfile,
  saveCompanyProfile,
  getClients,
  saveClient,
  deleteClient,
  getProducts,
  saveProduct,
  deleteProduct,
  updateProductStock,
  getBills,
  saveBill,
  deleteBill,
  getBillCounter,
  incrementBillCounter,
  updateBillPayment,
  uploadProductImage,
  getInventoryTransactions,
  saveInventoryTransaction,
  addStockToProduct,
  getProductTransactions,
  getPurchaseBills,
  savePurchaseBill,
  deletePurchaseBill,
  updatePurchaseBillPayment,
  deletePurchaseBillPayment,
  savePurchaseReturn,
  deletePurchaseReturn,
  addPurchaseItemsToInventory,
  isPurchaseBillDuplicate,
  isPurchaseBillInventoryAdded,
  updatePurchaseBillOverdueStatus,
  updatePurchaseBill,
  checkStockAvailability,
  validateBillStock,
  getBillReturns,
  saveBillReturn,
  getPurchaseReturns,
  getDeadstock,
  saveDeadstockItem,
  processBillReturn,
  updateBillAfterReturn,
  getBillReturnsByBillId,
  getReturnedQuantity,
  getCreators,
  saveCreator,
  deleteCreator,
  getTotalDeadstockLoss,
  getCostOfGoodsSold,
  getUserPreference,
  setUserPreference,
  getExpenses,
  saveExpense,
  deleteExpense,
  uploadFile,
  getFiles,
  deleteFile,
  downloadFile,
  getNotes,
  getNotesByDate,
  saveNote,
  deleteNote,
  updateNoteStatus,
  getProductSalesData,
  getSampleBills,
  deleteSampleBill,
  updateSampleBillPayment,
  saveSampleBill,
  getSampleBillCounter,
  incrementSampleBillCounter,
  type InventoryItemInput,
} from "./firebaseService";
